Feature/get exp from decoded token
soofstad/react-oauth2-pkce pull request #136
Opened 2024-02-15 15:51 UTC by anfreita

## What does this pull request change?
Add token `exp` claim as an additional fallback for determining token expiration

## Why is this pull request needed?
Some IdPs don't provide the `expires_in` field on token response

## Issues related to this change
https://github.com/soofstad/react-oauth2-pkce/issues/135

2024-02-16 06:53 UTC, soofstad requested changes

2024-02-16 06:53 UTC, soofstad commented on src/AuthContext.tsx
> +    const tokenExpiresIn = config.tokenExpiresIn
Looks good. Tested and seem to work as expected.
However, I think we should rearrange these setStates, so that you only decode the JWT once.

2024-02-16 09:34 UTC, sebastianvitterso commented
I would also like to point out that the pre-commit linting fails, as Biome wants to make some changes. 
I recommend installing [pre-commit](https://pre-commit.com/), and running `pre-commit install` inside the repository to initialize pre-commit hooks for the repo. 
This is, however, something we can fix for you before merging, if you'd prefer. 😄

2024-02-16 16:04 UTC, anfreita commented
@sebastianvitterso thanks for the tip. I've installed and run pre-commit and fixed the linting issues.

2024-02-16 16:08 UTC, anfreita commented on src/AuthContext.tsx
> +    const tokenExpiresIn = config.tokenExpiresIn
Good advice, I've moved the idTokenData setState up so now it only decodes the token once

2024-02-17 15:30 UTC, soofstad approved these changes
Looks good! Thanks a lot for your contribution :slightly_smiling_face:

2024-02-17 15:31 UTC, merged