feat: fix functions names & related terminology to be imperative
soofstad/react-oauth2-pkce pull request #142
Opened 2024-03-03 04:36 UTC by getsnoopy

## What does this pull request change?
This commit changes the `login` function to be `logIn`. It also updates any related terminology in the docs or otherwise to match.

## Why is this pull request needed?
Function names should conventionally be in the imperative form, but the login() function didn't conform to this convention.

## Issues related to this change
#115

2024-03-04 09:03 UTC, sebastianvitterso requested changes
Almost perfect! Thanks for the PR, just a few notes and I think we can merge it!

2024-03-04 09:03 UTC, sebastianvitterso commented on src/Types.ts
>    login: (state?: string) => void
```suggestion
  token: string
  logIn: (state?: string) => void
  logOut: (state?: string, logoutHint?: string) => void
  /** @deprecated use `logIn` instead */
  login: (state?: string) => void
```

Adding this line will show this to users still using `login`, which will help adoption of updated method:
![image](https://github.com/soofstad/react-oauth2-pkce/assets/37065184/c0efe5d1-f338-4bb5-a90e-19520863b000)

2024-03-04 09:03 UTC, sebastianvitterso commented on src/Types.ts
>    login: (state?: string) => void
I also see that we should have written similar messages on the other deprecated/replaced properties @soofstad. I'll make a PR for that once this one is merged/closed.

2024-03-04 09:03 UTC, sebastianvitterso commented on src/Types.ts
> +  logIn: () => void
This change is breaking, if any users still have `event.login`, that code won't work.

![image](https://github.com/soofstad/react-oauth2-pkce/assets/37065184/1831d452-5d87-4336-bff6-67df0d774146)

Do like in the above code, and have both available, but deprecate the one that's written wrong.

2024-03-04 09:03 UTC, sebastianvitterso commented on src/Types.ts
> +  logIn: () => void
I do appreciate this, however
![image](https://github.com/soofstad/react-oauth2-pkce/assets/37065184/c2953b1d-c407-475c-add0-400015f97971)

So just add the `login` as a deprecated property to the type, and we'll be there.

2024-03-16 10:00 UTC, soofstad commented
Thanks for the PR, I have nothing to add beyond Sebastians review.
Let's fixed that, and it's ready for merge :slightly_smiling_face:

2024-04-05 02:35 UTC, getsnoopy commented
Yeah; just been busy with work and life. I can get to this next week.

2024-05-10 00:13 UTC, getsnoopy commented
Apologies for the delay. I've updated the code now.

2024-05-10 05:42 UTC, sebastianvitterso approved these changes
Nice, thanks!

2024-05-10 05:50 UTC, soofstad approved these changes

2024-05-10 05:50 UTC, merged