Feat: add support to refresh token absolute lifetime
soofstad/react-oauth2-pkce pull request #168
Opened 2024-05-30 08:42 UTC by kleysonfiretail

## What does this pull request change?

This pull request adds a new configuration option, `refreshTokenExpiryStrategy`. This option allows users to specify the refresh token expiration strategy, choosing between:

'**renewable**': The refresh token's expiration time is renewed each time it is used. 
'**absolute**': The refresh token's expiration time is fixed from its initial issuance and does not change.

## Why is this pull request needed?

We are currently using Auth0 with Absolute Expiration. Auth0 implements an absolute expiration strategy for refresh tokens, meaning the expiration time is fixed from the initial issuance and does not renew with each use. However, the library was designed with the assumption that the refresh token expiration would be renewed each time a new refresh token is requested.

This mismatch between the actual expiration behavior and the library's expectations is causing issues. The library incorrectly assumes the refresh token has a longer validity period than it actually does, leading to potential authentication failures when the refresh token expires earlier than anticipated.

By introducing the refreshTokenExpiryStrategy configuration option, we can ensure that the library can accurately handle both renewable and absolute expiration strategies, preventing such mismatches and improving compatibility with different OAuth2 providers like Auth0.

[Configure Refresh Token Expiration - Absolute Lifetime](https://auth0.com/docs/secure/tokens/refresh-tokens/configure-refresh-token-expiration) 

![image](https://github.com/soofstad/react-oauth2-pkce/assets/109530790/b0b2e26f-8c28-4344-a93e-f3d1103305da)

## Issues related to this change
https://github.com/soofstad/react-oauth2-pkce/discussions/167

2024-05-30 12:12 UTC, soofstad requested changes
Alright, if Auth0 would just respond with the expiry time... :disappointed: 
But since they do not, I guess this is the only option we got.

Well written pull-request :+1: 

Check one comment, the linting, and I will merge this

2024-05-30 12:12 UTC, soofstad commented on src/types.ts
> +  refreshTokenExpiryStrategy?: 'renewable' | 'absolute'
```suggestion
  refreshTokenExpiryStrategy: 'renewable' | 'absolute'
```
No need to make this optional internally

2024-05-30 19:24 UTC, sebastianvitterso approved these changes
Looks good to me! @soofstad merge at will

2024-05-31 10:58 UTC, soofstad approved these changes

2024-05-31 10:59 UTC, merged

2024-05-31 11:00 UTC, soofstad commented
Thank you for the contribution @kleysonfiretail :+1: