Fetch with credentials in postWithXForm()
soofstad/react-oauth2-pkce pull request #188
Opened 2024-09-26 08:24 UTC by MichaelRoosz

## What does this pull request change?
It enabled credentials when doing fetch requests.
Specifically it enables TLS client certificate authentication for OPTIONS requests in Firefox.
This fixes 403/forbidden errors, that would happen otherwise, since the request would be done without client certificate authentication and thus fail with 403 when using firefox.
 
## Why is this pull request needed?
When the server is enforcing client certificate authentication, we must set the fetch option "credentials" to "include", to ensure all browsers are allowing client certificate authentication. For example, this is required in Firefox for "OPTIONS" requests.

## Issues related to this change

This will require the server to response with proper CORS response headers, but this should already be the case (for example when using Keycloak).
If you prefer to make this configurable, I am willing to implement this, just let me know how you would like to implement it.

2024-09-27 07:40 UTC, soofstad commented
Hi @MichaelRoosz 
Thank you for the pull-request.
I like this addition, but it should definitely be a opt-in on a per-request basis.
Setting this as default for all request is a serious security problem.
If you update the PR with this change, and fix up the tests, I'll be happy to merge it :slightly_smiling_face:

2024-10-02 13:57 UTC, MichaelRoosz commented
Hello @soofstad,
thank you for your feedback.
I have updated the pr and made sure all tests are passing.

2024-10-02 15:41 UTC, MichaelRoosz commented
I updated it, now also includes a test.

2024-10-03 06:51 UTC, MichaelRoosz commented
The linting check should now also be fixed.

2024-10-03 07:00 UTC, soofstad requested changes
Looks good!
A few comments, and also, please update the documentation

2024-10-03 07:00 UTC, soofstad commented on src/authConfig.ts
> +    tokenRequestCredentials,
The pattern so far has been to set default values here, where we can, and not have the key nullable in the "TInternalConfig".

2024-10-03 07:00 UTC, soofstad commented on src/authentication.ts
> +function postTokenRequest(tokenEndpoint: string, tokenRequest: TTokenRequest, tokenRequestCredentials?: RequestCredentials): Promise<TTokenResponse> {
```suggestion
function postTokenRequest(tokenEndpoint: string, tokenRequest: TTokenRequest, credentials?: RequestCredentials): Promise<TTokenResponse> {
```
Since we'r already in the "postTokenRequest" function, this variable can be simplified

2024-10-03 07:00 UTC, soofstad commented on src/httpUtils.ts
> +    credentials,
Please use `credentials: credentials`. A bit more explicit IMO :slightly_smiling_face:

2024-10-03 07:00 UTC, soofstad commented on src/authentication.ts
> +  tokenRequestCredentials?: RequestCredentials
Since we'r in a "fetch" context, you can simplify this argument as "credentials".

2024-10-04 09:50 UTC, MichaelRoosz commented
Hello @soofstad,
thanks a lot for your feedback, I have updated the pull-request accordingly.
I have set the default to 'same-origin', since this is the default behaviour when the 'credential' property is not set (as documented here https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)

2024-10-04 11:23 UTC, soofstad approved these changes
Good, just one last thing

2024-10-04 11:23 UTC, soofstad commented on src/httpUtils.ts
> +  credentials?: RequestCredentials
Should not be optional here now, after changing the type in InternalConfig :slightly_smiling_face:

2024-10-04 11:23 UTC, soofstad commented on src/httpUtils.ts
> +    credentials: credentials ?? 'same-origin',
And therefore no need for this check

2024-10-04 11:23 UTC, soofstad commented on src/types.ts
> +  tokenRequestCredentials?: RequestCredentials
Same

2024-10-04 11:23 UTC, soofstad requested changes
See above comments

2024-10-04 15:49 UTC, MichaelRoosz commented
thank you @soofstad , I have updated the pr :)

2024-10-07 06:55 UTC, soofstad approved these changes
Good work! Thank you for the contribution :partying_face:

2024-10-07 06:56 UTC, merged