Popup window to be centred on screen
soofstad/react-oauth2-pkce pull request #198
Opened 2024-10-25 01:14 UTC by thejurassic

## What does this pull request change?
Popup window to be centred in the window (or screen)

## Why is this pull request needed?
Popup window is not centred, and would provide better user experience if centred on the page theyre working on that invoked the login

## Issues related to this change
None

2024-10-25 05:42 UTC, sebastianvitterso requested changes

2024-10-25 05:42 UTC, sebastianvitterso commented on src/authentication.ts
> +const stateStorageKey = "ROCP_auth_state";
I can tell you right now that you should try to run the installed pre-commit hooks, as all these changes go against the style guide in the repo 😄 

We'll look into the changes when the changes aren't all over!

2024-10-28 09:34 UTC, sebastianvitterso commented on src/authentication.ts
> +const stateStorageKey = "ROCP_auth_state";
I just went ahead and did that.

2024-11-04 14:15 UTC, sebastianvitterso commented
@thejurassic, are you still interested in this change?

2024-11-04 14:24 UTC, sebastianvitterso commented on src/authentication.ts
> +}
This should probably be moved to a separate utility-file, as it doesn't belong in `authentication.ts`, in our opinion.

2024-11-04 14:24 UTC, sebastianvitterso commented on src/authentication.ts
> +  const screenHeight = window.innerHeight || document.documentElement.clientHeight || screen.height
Will any of these actually be unset at any point? 

E.g. `screenLeft` vs `screenX` has basically the same stats on caniuse ([screenLeft](https://caniuse.com/mdn-api_window_screenleft), [screenX](https://caniuse.com/mdn-api_window_screenx)), and I assume the same may be true for the other 6 properties you've listed.

If so, let's just use the most "natural"/simple ones, and stick with those.

2024-11-04 14:24 UTC, sebastianvitterso commented on src/authentication.ts
> +  return { left, top, width: popupWidth, height: popupHeight }
This is cool and all, but if this is meant to fix all cases, what about the case where the screen is smaller than the dialog size? Then surely, we should resize the dialog to match the screen?

So

```js
const maxLeft = screenLeft + (screenWidth - popupWidth)
const maxTop = screenTop + (screenHeight - popupHeight)

return {
  left: Math.max(0, Math.min(left, maxLeft)),
  top: Math.max(0, Math.min(top, maxTop)),
  width: Math.min(screenWidth, popupWidth),
  height: Math.min(screenHeight, popupHeight),
}
```

2024-11-04 14:24 UTC, sebastianvitterso commented on src/authentication.ts
> +  const screenHeight = window.innerHeight || document.documentElement.clientHeight || screen.height
And as such, if these are set in (basically) all browsers, consider using them directly further down into the script.

2024-11-05 09:17 UTC, sebastianvitterso commented on src/authentication.ts
> +  return { left, top, width: popupWidth, height: popupHeight }
Did this myself  ✌️

2024-11-05 09:17 UTC, sebastianvitterso commented on src/authentication.ts
> +  const screenHeight = window.innerHeight || document.documentElement.clientHeight || screen.height
Did this myself  ✌️

2024-11-05 09:17 UTC, sebastianvitterso commented on src/authentication.ts
> +}
Did this myself  ✌️

2024-11-05 09:37 UTC, soofstad approved these changes
Looks good! Tested OK.
Thank you for the contribution @thejurassic :tada:

2024-11-05 09:38 UTC, merged